### ISSUE TITLE
IllegalStateException: The view is currently not attached. Caused by click listeners

### ISSUE THREAD

**Issue by ar-g** [grandcentrix/ThirtyInch#104]
We have in our crashlytics some NPE crashes caused by onClickListeners in ViewHolders and Fragments. They ain't many but still occurs. Do you have any idea why? 
```java
Fatal Exception: java.lang.IllegalStateException: The view is currently not attached. Use 'sendToView(ViewAction)' instead.
       at net.grandcentrix.thirtyinch.f.Q(TiPresenter.java:334)
       at classifieds.yalla.features.chats.chat.regular.i.p(ChatPresenter.java:207)
       at classifieds.yalla.features.chats.chat.regular.ChatFragment.b(ChatFragment.java:109)
       at classifieds.yalla.features.chats.chat.regular.a.onClick(Unknown Source)
       at android.view.View.performClick(View.java:4475)
       at android.view.View$PerformClick.run(View.java:18786)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by passsy** [comment]
You're running asynchronous code in your presenter. The user removed your fragment somehow (or closed the app) and the view was detached (`onDetachView()`). Then your async code returns and calls `getViewOrThrow()`. The view is detached and `null`.

As mentioned in the error message you should use `sendToView(v -> v.callYourMethod())` instead of `getViewOrThrow().callYourMethod()`
